update cacheing

diff --git a/ansible/roles/k3s-agent/tasks/cache_container_image.yml b/ansible/roles/k3s-agent/tasks/cache_container_image.yml
--- a/ansible/roles/k3s-agent/tasks/cache_container_image.yml
+++ b/ansible/roles/k3s-agent/tasks/cache_container_image.yml
@@ -13,28 +13,51 @@
     path: /vagrant/cache/images
     state: directory
 
-- name: cache {{ item }} container image, if it exists in docker storage
+- name: save {{ item }} container image to cache 
   shell: |
-    image="{{ item }}"
-    IFS=':' read -r -a parts <<< "${image}"
+    tempfile=$(mktemp /tmp/nemonik.XXXXXXXXXX)
 
-    tag="${parts[1]}"
+    trap "{ rm -f $tempfile; }" EXIT
 
-    filter="{{ "{{" }}.Repository{{ "}}" }}"
+    image="{{ item.repository }}"
 
-    if [ ! -z "$tag" ]; then
-      filter="${filter}:{{ "{{" }}.Tag{{ "}}" }}"
+    if [ ! -z "{{ item.tag }}" ]; then
+      image="${image}:{{ item.tag }}"
     fi
 
-    IFS=':' read -r -a parts <<< "$(docker image ls ${image} --format "${filter}")"
+    filter="{{ "{{" }}.Repository{{ "}}:{{" }}.Tag{{ "}}" }}"
 
-    if [ ! -z "${parts}" ]; then
-      archive_name=${image/\//_}
-      archive_name=${archive_name/:/_}
+    retries={{ default_retries }}
+    found=false
+    image_in_docker_storage=""
+    until [  $retries == 0 ]; do
+      let retries-=1
 
-      if [ -f "/vagrant/cache/${archive_name}.tar.gz" ]; then
-        docker save ${image} | gzip -c > /vagrant/cache/images/${archive_name}.tar.gz
+      image_in_docker_storage="$(docker image ls ${image} --format "${filter}")"
+
+      if [ ! -z "${image_in_docker_storage}" ]; then
+        found=true
+        break
+      else
+        sleep {{ default_delay }}
       fi
+    done
+
+    if [[ "${found}" == true ]]; then
+      archive_name=${image_in_docker_storage/\//%2F}
+      archive_name=${archive_name/:/%3A}
+
+      if [ ! -f "/vagrant/cache/images/${archive_name}.tar" ]; then
+        docker save ${image_in_docker_storage} > $tempfile
+        if [[ "windows" == "{{ host_os }}" ]]; then
+          sudo su;
+        fi
+        cp -f $tempfile /vagrant/cache/images/${archive_name}.tar
+      else 
+        echo "${image_in_docker_storage} is already cached."
+      fi
+    else
+      echo "${image} not found in Docker storage."
     fi
   args:
     executable: /bin/bash
